### ISSUE TITLE
Feature change request for video player

### ISSUE THREAD

**Issue by ujepx64** [gkisalatiga/gkisalatiga-foss#51]
Using a default youtube player ui

**Comment by groaking** [comment]
Bang @ujepx64, aku mikirnya nanti mbikin pengaturan di aplikasi GKI Salatiga+.
Terus nanti pengguna bisa milih, mau pakai pemutar baru atau lama.
Defaultnya tetap yang pemutar baru.

Gitu aja gimana bang?

**Comment by ujepx64** [comment]
Boleh bang @groaking , dicoba dulu aja

**Comment by groaking** [comment]
Done 5f48ba1f4370d47c3430d6ba2910abe2c13eecc0
