### ISSUE TITLE
Fix schedule for "agenda mingguan"

### ISSUE THREAD

**Issue by ujepx64** [gkisalatiga/gkisalatiga-foss#57]
- English service (tiap minggu pertama) pukul 10.00 di Ruang Kana
- Ibadah Komisi Remaja pukul 07.30 di Ruang Kana

Request:
Jadwal event khusus bulan keluarga (coming soon)

**Comment by groaking** [comment]
Fixed in [v0.5.0-rc update](https://github.com/gkisalatiga/gkisalatiga-foss/releases/tag/v0.5.0-rc)
