### ISSUE TITLE
E book feature

### ISSUE THREAD

**Issue by ujepx64** [gkisalatiga/gkisalatiga-foss#60]
1. ebook kedukaan GKIS
2. ebook lainnya

> membuat` tombol menu baru di beranda

**Comment by groaking** [comment]
Done in 13248982ce3c8a796df7ea5cda45cbfff17738e1, fa9a3b6379231ce268079e695fda0aaf07a5d9cc, and 2f7328f96ee9e8bdfd80487b26693296ac7b1d03

**Comment by groaking** [comment]
@ujepx64 ebook kedukaan GKIS kayaknya harus nunggu surat izin dari YAMUGER. Nanti biar MJ yang bersurat.
