### ISSUE TITLE
Quick navigation bar

### ISSUE THREAD

**Issue by ujepx64** [gkisalatiga/gkisalatiga-foss#63]
Quick navigation bar ke page/konten yang sering dicari/dipakai

@ujepx64 idk with this :D

**Comment by groaking** [comment]
Sepertinya agak sulit. Pertimbangannya, nanti juga perlu membuat fitur "menu mana yang ingin ditampilkan/disembunyikan di halaman depan" (mirip @gojek). Jadi perlu pembuatan akun.

Masalahnya juga, ini berarti kita mengumpulkan _user analytics_: fitur mana yang paling banyak/paling sering dipakai oleh pengguna. Saat ini analitik belum bisa direalisasi, karena harus membuat API endpoint di `gkisalatiga.org`.

Mungkin dalam satu atau dua tahun ke depan ini bisa terwujud. Tetapi dalam waktu dekat, kita masih perlu fokus membuat Simon Petrus versi web.

**Comment by groaking** [comment]
Isunya nanti dibuka lagi saat Simon Petrus web sudah jadi.
