### ISSUE TITLE
Bug on fullscreen youtube player (especially from opening saren notification)

### ISSUE THREAD

**Issue by ujepx64** [gkisalatiga/gkisalatiga-foss#72]

**Comment by groaking** [comment]
Bang @ujepx64, sudah diperbaiki bugnya di #73. Mau dibikin APK terus distribusi di internal dev, atau sekalian bareng update yang lain di versi `0.6.0-rc`?

**Comment by ujepx64** [comment]
Sekalian `v0.6.0-rc` saja

**Comment by groaking** [comment]
Wokeyyy bang Jeff. Thank you..
